-- Forever Frame Builder
-- Exporter: turns a project into plain Lua code and into a shareable import string.

local _, ns = ...
local L = ns.L
local Doc = ns.Doc

local Exporter = {}
ns.Exporter = Exporter

local SHARE_PREFIX = "MFB1:"

local function ElementVar(node)
	return "E." .. node.name
end

local function ParentVar(node)
	local parent = Doc:Get(node.parent)
	if not parent then
		return "UIParent"
	end
	local childKey = ns.Elements[parent.type].childKey
	return ElementVar(parent) .. (childKey and ("." .. childKey) or "")
end

local function ExportScripts(out, node, def)
	local v = ElementVar(node)
	for _, script in ipairs(def.scripts) do
		local code = node.scripts[script.name]
		if code and code ~= "" then
			-- OnLoad runs once right away, with self bound to the element.
			if script.name == "OnLoad" then
				out("do")
				out("\tlocal self = " .. v)
			elseif script.method then
				out(v .. "." .. script.name .. " = function(" .. script.args .. ")")
			else
				out(v .. ":HookScript(" .. ns.LuaStr(script.name) .. ", function(" .. script.args .. ")")
			end
			for line in (code .. "\n"):gmatch("(.-)\r?\n") do
				out(line ~= "" and ("\t" .. line) or "")
			end
			out((script.name == "OnLoad" or script.method) and "end" or "end)")
		end
	end
end

-- Generates standalone Lua code that recreates the current project.
function Exporter:ToLua()
	local lines = {}
	local function out(line)
		lines[#lines + 1] = line
	end

	out(("-- %s"):format(Doc:CurrentName()))
	out(("-- Generated by %s %s"):format(ns.title, ns.version))
	out("-- Every element is stored in the table E under its name, e.g. E.MyFrame.")
	out("")
	out("local E = {}")
	out("")

	local withScripts, afterChildren = {}, {}
	local created, deferredAnchors = {}, {}
	Doc:Walk(function(node)
		local def = ns.Elements[node.type]
		local v = ElementVar(node)
		local parentVar = ParentVar(node)
		out(("-- %s (%s)"):format(node.name, def.label))
		if def.region then
			out(def.ExportCreate(v, parentVar, node.props))
		else
			local globalName = node.globalName ~= "" and ns.LuaStr(node.globalName) or "nil"
			local templateName = def.template
			if def.ExportTemplate then
				templateName = def.ExportTemplate(node.props)
			end
			local template = templateName and (", " .. ns.LuaStr(templateName)) or ""
			local frameType = def.ExportFrameType and def.ExportFrameType(node.props) or def.frameType
			out(("%s = CreateFrame(%s, %s, %s%s)"):format(v, ns.LuaStr(frameType), globalName, parentVar, template))
		end
		if node.fill then
			out(("%s:SetAllPoints(%s)"):format(v, parentVar))
		else
			out(("%s:SetSize(%s, %s)"):format(v, ns.LuaNum(node.w), ns.LuaNum(node.h)))
			-- Anchors to elements that are created later can only be set once all exist.
			local lines, later = {}, false
			for _, anchor in ipairs(Doc.GetAnchors(node)) do
				local target = Doc:ResolveAnchorTarget(node, anchor.target)
				local relative = target and ElementVar(Doc:Get(target)) or parentVar
				if target and not created[target] then
					later = true
				end
				table.insert(lines, ("%s:SetPoint(%s, %s, %s, %s, %s)"):format(v, ns.LuaStr(anchor.point), relative,
					ns.LuaStr(anchor.relPoint), ns.LuaNum(anchor.x), ns.LuaNum(anchor.y)))
			end
			for _, line in ipairs(lines) do
				if later then
					table.insert(deferredAnchors, line)
				else
					out(line)
				end
			end
		end
		if node.strata ~= "" and not def.region then
			out(v .. ":SetFrameStrata(" .. ns.LuaStr(node.strata) .. ")")
		end
		if node.alpha ~= 1 then
			out(v .. ":SetAlpha(" .. ns.LuaNum(node.alpha) .. ")")
		end
		def.Export(out, v, node.props, node)
		if not node.shown then
			out(v .. ":Hide()")
		end
		out("")
		if next(node.scripts) then
			table.insert(withScripts, node)
		end
		if def.ExportAfterChildren then
			table.insert(afterChildren, node)
		end
		created[node.id] = true
	end)

	if #deferredAnchors > 0 then
		out("-- Anchors to elements created further down")
		for _, line in ipairs(deferredAnchors) do
			out(line)
		end
		out("")
	end

	for _, node in ipairs(afterChildren) do
		local childVars = {}
		for i, childId in ipairs(node.children) do
			childVars[i] = ElementVar(Doc:Get(childId))
		end
		out(("-- %s: children"):format(node.name))
		ns.Elements[node.type].ExportAfterChildren(out, ElementVar(node), node.props, node, childVars)
		out("")
	end

	if #withScripts > 0 then
		out("-- Scripts")
		for _, node in ipairs(withScripts) do
			ExportScripts(out, node, ns.Elements[node.type])
		end
		out("")
	end

	return table.concat(lines, "\n")
end

---------------------------------------------------------------------------
-- Share strings
---------------------------------------------------------------------------

function Exporter:CanShare()
	local util = C_EncodingUtil
	return util and util.SerializeCBOR and util.DeserializeCBOR and util.CompressString
		and util.DecompressString and util.EncodeBase64 and util.DecodeBase64 and true or false
end

function Exporter:ToString()
	local project = Doc.project
	local list = {}
	for _, node in pairs(project.nodes) do
		table.insert(list, node)
	end
	local payload = { v = 1, name = Doc:CurrentName(), roots = project.roots, nodes = list }
	local ok, result = pcall(function()
		local data = C_EncodingUtil.SerializeCBOR(payload)
		data = C_EncodingUtil.CompressString(data)
		return C_EncodingUtil.EncodeBase64(data)
	end)
	if not ok then
		return nil, tostring(result)
	end
	return SHARE_PREFIX .. result
end

-- Returns name, project or nil, errorMessage.
function Exporter:FromString(text)
	text = strtrim(text or ""):gsub("%s", "")
	if text:sub(1, #SHARE_PREFIX) ~= SHARE_PREFIX then
		return nil, L["This is not a Frame Builder string."]
	end
	local ok, payload = pcall(function()
		local data = C_EncodingUtil.DecodeBase64(text:sub(#SHARE_PREFIX + 1))
		data = C_EncodingUtil.DecompressString(data)
		return C_EncodingUtil.DeserializeCBOR(data)
	end)
	if not ok or type(payload) ~= "table" or type(payload.nodes) ~= "table" or type(payload.roots) ~= "table" then
		return nil, L["The string could not be decoded."]
	end

	local nodes = {}
	for _, node in ipairs(payload.nodes) do
		if type(node) == "table" and type(node.id) == "number" and type(node.name) == "string"
			and ns.Elements[node.type] then
			node.props = type(node.props) == "table" and node.props or {}
			node.scripts = type(node.scripts) == "table" and node.scripts or {}
			node.children = type(node.children) == "table" and node.children or {}
			nodes[node.id] = node
		end
	end
	-- Rebuild the tree from the roots so dangling ids, duplicates and cycles are dropped.
	local visited = {}
	local function Adopt(list, parentId)
		local result = {}
		for _, id in ipairs(list) do
			local node = nodes[id]
			if node and not visited[id] then
				visited[id] = true
				node.parent = parentId
				table.insert(result, id)
				node.children = Adopt(node.children, id)
			end
		end
		return result
	end
	local roots = Adopt(payload.roots, nil)
	for id in pairs(nodes) do
		if not visited[id] then
			nodes[id] = nil
		end
	end
	local project = { nodes = nodes, roots = roots, nextId = 1 }
	local name = type(payload.name) == "string" and payload.name or L["Imported"]
	return name, project
end

function Exporter:CountScripts(project)
	local count = 0
	for _, node in pairs(project.nodes) do
		for _, code in pairs(node.scripts) do
			if type(code) == "string" and code ~= "" then
				count = count + 1
			end
		end
	end
	return count
end
